### ISSUE TITLE
Add normalize_tweets_v2 or something like this

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/twitwi#10]
Au fait @bmaz @boogheta vous avez vu les clés `unwound_url` comme là: https://github.com/medialab/twitwi/blob/7c19c5e4d91531933ad89c279263ea346787a0e8/test/resources/payload_v2.json#L130 ? Plus besoin de faire le resolving avec la v2?

**Comment by boogheta** [comment]
Il me semble que ces champs ne sont pas accessibles à tous, mais réservé aux accès payants à l'API. Mais peut-être que le payload d'exemple de @bmaz vient d'un appel "recherche" et que ceux là bénéficient aussi de cela ?
Auquel cas effectivement une future version de gazouilloire utilisant l'api v2 pourra s'abstraire du resolving conditionnellement pour les cas de clés recherche

**Comment by bmaz** [comment]
J'ai testé avec ta clef, Benjamin, j'ai trouvé des unwound_urls, donc je pense que ça marche aussi quand on n'a pas un accès recherche

**Comment by boogheta** [comment]
ha intéressant !
C'est un output de quelle route ?
Parce que je n'ai pas ce champ moi dans les outputs de la routes "tweets" par liste d'ids

**Comment by bmaz** [comment]
`curl "https://api.twitter.com/2/tweets/search/recent?query=python&max_results=10&tweet.fields=attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,reply_settings,source,text,withheld&media.fields=duration_ms,height,media_key,preview_image_url,type,url,width,public_metrics&place.fields=contained_within,country,country_code,full_name,geo,id,name,place_type&poll.fields=duration_minutes,end_datetime,id,options,voting_status&user.fields=created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld&expansions=attachments.poll_ids,attachments.media_keys,author_id,entities.mentions.username,geo.place_id,in_reply_to_user_id,referenced_tweets.id,referenced_tweets.id.author_id" -H "Authorization: Bearer $BEARER_TOKEN" | json_pp -json_opt pretty,canonical > payload_v2_Benjamin.json`

**Comment by boogheta** [comment]
Il faudra récupérer et normaliser aussi les éléments des context_annotations : https://developer.twitter.com/en/docs/twitter-api/annotations
