### ISSUE TITLE
Is this normal for tests not to be idempotent regarding server world location if locale is None?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/twitwi#17]

**Comment by boogheta** [comment]
maybe rather setup tests with specific locales set then ?

**Comment by Yomguithereal** [comment]
It is not an issue for the CI test, as we can just pass the locale to be used. It is rather an open question: is this normal for our functions to return different results when given locale is `None`? Shouldn't it be normalized to UTC in that case?

**Comment by boogheta** [comment]
ha yes indeed, I guess this would sound reasonable. At least in gazouilloire the default config has a locale set so people will always end up on french time if they don't adjust it, but indeed in other usecases people might not set it and it would make sense then to use an universal time

**Comment by Yomguithereal** [comment]
Ok then the culprit is this line here: https://github.com/medialab/twitwi/blob/master/twitwi/utils.py#L33 if `astimezone` is fed with a `None` locale it returns something based on the computer's locale.

@bmaz what do you think? Should we switch to return the `locale_datetime` as UTC when `locale` is not provided or default.

In which case I should configure minet to get your computer's locale? Or should I let minet output UTC by default but let users tell me if they want a specific locale?

**Comment by boogheta** [comment]
I don't understand @Yomguithereal, the line you're pointing with a surrounding "if locale:" so in case of None this line shouldn't be ran and we should default to parsed_datetime no?

**Comment by Yomguithereal** [comment]
I agree with you, so there is something fishy going on elsewhere because I don't have the same results with locale to `None` on my computer and on CI servers. Are python `datetime` by default formatting dates based on computer locale per chance?

**Comment by boogheta** [comment]
Reading answers [here](https://stackoverflow.com/questions/3305413/python-strptime-and-timezones) it seems like strptime uses locale when the iso datetime parsed contains the Z part which I believe twitter does, so maybe this explains that?

**Comment by Yomguithereal** [comment]
So I guess we should just switch to a default locale being the UTC locale instead of `None`. Better safe than sorry no?

**Comment by boogheta** [comment]
sounds ok to me
