### ISSUE TITLE
media file names contain ?tag=...

### ISSUE THREAD

**Issue by bmaz** [medialab/twitwi#29]
This may be a twitwi problem or a gazouilloire problem. We should investigate.

**Comment by boogheta** [comment]
actually it is a past problem from gazouilloire 0.1, but it is already handled properly in 1.0 thanks to twitwi, cf https://github.com/medialab/twitwi/blob/ac98801986e624aed4c54345f6a7efc0b779a243/twitwi/normalizers.py#L43
