### ISSUE TITLE
Missing data from twitter API v2 regarding user_metrics

### ISSUE THREAD

**Issue by boogheta** [medialab/twitwi#55]
```
  File "/home/kelly.christensen/.pyenv/versions/3.10.6/envs/medias/lib/python3.10/site-packages/twitwi/normalizers.py", line 687, in normalize_tweet_v2
    'user_lists': user_public_metrics['listed_count'],
KeyError: 'listed_count'
```

We shall use a .get instead of direct access to the keys there

**Comment by Yomguithereal** [comment]
Shall I pass all the `user_public_metrics` as using a `.get` you think, to be futureproof at the expense of maybe don't noticing future consistency issues? Or do I apply this only to `listed_count`?

**Comment by boogheta** [comment]
i would yes
